/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/backtest/pla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest Pla
         * @description P&L attribution: Spearman and KS between daily hypothetical and
         *     risk-theoretical P&L with MAR32-style zones. Shipped with the options
         *     sleeve, which gives the statistic structural content beyond the linear
         *     legs' log-linearization.
         */
        get: operations["backtest_pla_api_v1_backtest_pla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest Summary
         * @description Kupiec, Christoffersen and the Basel traffic light over the trailing
         *     exception series (observed P&L vs the prior day's VaR).
         */
        get: operations["backtest_summary_api_v1_backtest_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/desks/{desk_code}/decomposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Desk Decomposition
         * @description VaR-decomposition waterfall (factor-class buckets + diversification) and
         *     the desk's factor exposures. Buckets are empty for runs without the position
         *     step (backfill runs) - the desk VaR itself is still reported.
         */
        get: operations["desk_decomposition_api_v1_desks__desk_code__decomposition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/desks/{desk_code}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Desk Positions
         * @description Per-position standalone/component/marginal VaR for one desk (no
         *     pagination - the book is under 100 rows by construction).
         */
        get: operations["desk_positions_api_v1_desks__desk_code__positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factors/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Factors Latest
         * @description Latest level and day move per active factor - the dashboard's factor
         *     tape. Moves are reported in each factor's own convention units.
         */
        get: operations["factors_latest_api_v1_factors_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Bootstrap payload: latest completed batch, run-date catalog, desks.
         */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modeldoc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Modeldoc
         * @description The SR 11-7-structured model document, verbatim markdown.
         */
        get: operations["modeldoc_api_v1_modeldoc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/exposures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Risk Exposures
         * @description Key-rate DV01s per desk from the run's bootstrapped par curve - empty
         *     rows for runs that skip the curve step (backfill runs do).
         */
        get: operations["risk_exposures_api_v1_risk_exposures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Risk History
         * @description 1-day VaR/ES, P&L and exception flags per date for one scope - the
         *     timeline and sparkline feed.
         */
        get: operations["risk_history_api_v1_risk_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Risk Movers
         * @description Desk VaR moves vs the run `window` days back, with the as-of day's
         *     largest factor moves as driver strings - the Overview movers table.
         *     Empty rows on the first run.
         */
        get: operations["risk_movers_api_v1_risk_movers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Risk Summary
         * @description Firm and per-desk VaR/ES with limits, utilization, day-over-day moves
         *     and the diversification benefit - the dashboard tiles in one call.
         */
        get: operations["risk_summary_api_v1_risk_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scenarios Catalog
         * @description Scenario definitions: replay windows and hypothetical shock lists (the
         *     dashboard formats dominant-move strings from these).
         */
        get: operations["scenarios_catalog_api_v1_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scenarios Results
         * @description Scenario catalog with per-desk P&L impacts from the latest run that
         *     executed scenarios (EOD runs do; backfill runs don't), worst first.
         */
        get: operations["scenarios_results_api_v1_scenarios_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness plus a database round-trip.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestException */
        BacktestException: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Pnl Value */
            pnl_value: number;
            /** Var Value */
            var_value: number;
        };
        /** BacktestSummary */
        BacktestSummary: {
            christoffersen_cc: components["schemas"]["LRTest"];
            christoffersen_independence: components["schemas"]["LRTest"];
            /**
             * End
             * Format: date
             */
            end: string;
            /** Exceptions */
            exceptions: components["schemas"]["BacktestException"][];
            /** Expected Exceptions */
            expected_exceptions: number;
            kupiec: components["schemas"]["LRTest"];
            /** Measure */
            measure: string;
            /**
             * Model
             * @enum {string}
             */
            model: "HS" | "FHS";
            /** N Exceptions */
            n_exceptions: number;
            /** N Obs */
            n_obs: number;
            /** Scope */
            scope: string;
            /**
             * Start
             * Format: date
             */
            start: string;
            traffic_light: components["schemas"]["TrafficLight"];
            /** Window */
            window: number;
        };
        /** Desk */
        Desk: {
            /** Desk Code */
            desk_code: string;
            /** Desk Name */
            desk_name: string;
            /** Is Aggregate */
            is_aggregate: boolean;
        };
        /** DeskBucket */
        DeskBucket: {
            /** Factor Class */
            factor_class: string;
            /** Standalone Var */
            standalone_var: number;
        };
        /** DeskDecomposition */
        DeskDecomposition: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Buckets */
            buckets: components["schemas"]["DeskBucket"][];
            /** Desk Code */
            desk_code: string;
            /** Desk Name */
            desk_name: string;
            /** Diversification */
            diversification: number | null;
            /** Exposures */
            exposures: components["schemas"]["DeskExposure"][];
            /** Run Id */
            run_id: number;
            /** Var Hs 1D */
            var_hs_1d: number | null;
        };
        /** DeskExposure */
        DeskExposure: {
            /** Factor Code */
            factor_code: string;
            /** Measure */
            measure: string;
            /** Tenor Years */
            tenor_years: number | null;
            /** Value */
            value: number;
        };
        /** DeskPosition */
        DeskPosition: {
            /** Component Es */
            component_es: number;
            /** Factor Class */
            factor_class: string;
            /** Factor Code */
            factor_code: string | null;
            /** Instrument Type */
            instrument_type: string;
            /** Marginal Var */
            marginal_var: number;
            /** Maturity Years */
            maturity_years: number | null;
            /** Moneyness */
            moneyness: number | null;
            /** Option Type */
            option_type: string | null;
            /** Pct Of Desk */
            pct_of_desk: number | null;
            /** Quantity */
            quantity: number;
            /** Standalone Var */
            standalone_var: number;
            /** Ticker */
            ticker: string;
        };
        /** DeskPositions */
        DeskPositions: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Desk Code */
            desk_code: string;
            /** Desk Name */
            desk_name: string;
            /** Positions */
            positions: components["schemas"]["DeskPosition"][];
            /** Run Id */
            run_id: number;
        };
        /** DeskRisk */
        DeskRisk: {
            /** Desk Code */
            desk_code: string;
            /** Desk Name */
            desk_name: string;
            /** Es 975 10D */
            es_975_10d?: number | null;
            /** Es 975 1D */
            es_975_1d?: number | null;
            /** Es Stressed 1D */
            es_stressed_1d?: number | null;
            /** Is Aggregate */
            is_aggregate: boolean;
            /** Limit Status */
            limit_status?: ("OK" | "WARN" | "BREACH") | null;
            /** Limit Value */
            limit_value?: number | null;
            /** Utilization */
            utilization?: number | null;
            /** Var Dod */
            var_dod?: number | null;
            /** Var Fhs 10D */
            var_fhs_10d?: number | null;
            /** Var Fhs 1D */
            var_fhs_1d?: number | null;
            /** Var Hs 10D */
            var_hs_10d?: number | null;
            /** Var Hs 1D */
            var_hs_1d?: number | null;
        };
        /** FactorTick */
        FactorTick: {
            /** Change */
            change: number | null;
            /** Factor Code */
            factor_code: string;
            /** Factor Type */
            factor_type: string;
            /** Level */
            level: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "%" | "bp" | "pt";
        };
        /** FactorsLatest */
        FactorsLatest: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Run Id */
            run_id: number;
            /** Ticks */
            ticks: components["schemas"]["FactorTick"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Healthz */
        Healthz: {
            /**
             * Database
             * @constant
             */
            database: "ok";
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Es 975 */
            es_975: number | null;
            /** Exception Fhs */
            exception_fhs: boolean;
            /** Exception Hs */
            exception_hs: boolean;
            /** Pnl */
            pnl: number | null;
            /** Var Fhs */
            var_fhs: number | null;
            /** Var Hs */
            var_hs: number | null;
        };
        /** KeyRateExposures */
        KeyRateExposures: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Rows */
            rows: components["schemas"]["KeyRateRow"][];
            /** Run Id */
            run_id: number;
            /** Unit */
            unit: string;
            /** Vega */
            vega: components["schemas"]["VegaExposure"][];
        };
        /** KeyRateRow */
        KeyRateRow: {
            /** Desk Code */
            desk_code: string;
            /** Factor Code */
            factor_code: string;
            /** Tenor Years */
            tenor_years: number;
            /** Value */
            value: number;
        };
        /** LRTest */
        LRTest: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Df */
            df: number;
            /** Name */
            name: string;
            /** P Value */
            p_value: number;
            /** Reject 5Pct */
            reject_5pct: boolean;
            /** Statistic */
            statistic: number;
        };
        /** Meta */
        Meta: {
            /** Available Dates */
            available_dates: string[];
            /** Batch Completed At */
            batch_completed_at: string | null;
            /** Batch Status */
            batch_status: string;
            /** Batch Type */
            batch_type: string | null;
            /** Code Version */
            code_version: string | null;
            /** Desks */
            desks: components["schemas"]["Desk"][];
            /** Latest As Of */
            latest_as_of: string | null;
        };
        /** ModelDoc */
        ModelDoc: {
            /** Markdown */
            markdown: string;
        };
        /** MoverRow */
        MoverRow: {
            /** Delta Pct */
            delta_pct: number | null;
            /** Delta Usd */
            delta_usd: number;
            /** Desk Code */
            desk_code: string;
            /** Drivers */
            drivers: string[];
        };
        /** PlaPoint */
        PlaPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Hpl */
            hpl: number;
            /** Rtpl */
            rtpl: number;
        };
        /** PlaSummary */
        PlaSummary: {
            /**
             * End
             * Format: date
             */
            end: string;
            /** Ks */
            ks: number;
            /** N Obs */
            n_obs: number;
            /** Points */
            points: components["schemas"]["PlaPoint"][];
            /** Scope */
            scope: string;
            /** Spearman */
            spearman: number;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Window */
            window: number;
            /**
             * Zone
             * @enum {string}
             */
            zone: "GREEN" | "AMBER" | "RED";
        };
        /** RiskHistory */
        RiskHistory: {
            /**
             * End
             * Format: date
             */
            end: string;
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
            /** Scope */
            scope: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** RiskMovers */
        RiskMovers: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Prev Date */
            prev_date: string | null;
            /** Rows */
            rows: components["schemas"]["MoverRow"][];
            /** Run Id */
            run_id: number;
        };
        /** RiskSummary */
        RiskSummary: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Desks */
            desks: components["schemas"]["DeskRisk"][];
            /** Diversification Benefit */
            diversification_benefit: number | null;
            /** Run Id */
            run_id: number;
            /** Run Type */
            run_type: string;
            /** Status */
            status: string;
        };
        /** ScenarioCatalog */
        ScenarioCatalog: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioSpec"][];
        };
        /** ScenarioResult */
        ScenarioResult: {
            /** Description */
            description: string | null;
            /** Firm Impact */
            firm_impact: number | null;
            /** Impacts */
            impacts: {
                [key: string]: number;
            };
            /** Scenario Code */
            scenario_code: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Type */
            scenario_type: string;
            /** Window End */
            window_end: string | null;
            /** Window Start */
            window_start: string | null;
            /** Worst Desk */
            worst_desk: string | null;
        };
        /** ScenarioResults */
        ScenarioResults: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Results */
            results: components["schemas"]["ScenarioResult"][];
            /** Run Id */
            run_id: number;
        };
        /** ScenarioShock */
        ScenarioShock: {
            /** Factor Code */
            factor_code: string;
            /** Shock Type */
            shock_type: string;
            /** Shock Value */
            shock_value: number;
        };
        /** ScenarioSpec */
        ScenarioSpec: {
            /** Description */
            description: string | null;
            /** Scenario Code */
            scenario_code: string;
            /** Scenario Name */
            scenario_name: string;
            /** Scenario Type */
            scenario_type: string;
            /** Shocks */
            shocks: components["schemas"]["ScenarioShock"][];
            /** Window End */
            window_end: string | null;
            /** Window Start */
            window_start: string | null;
        };
        /** TrafficLight */
        TrafficLight: {
            /** Multiplier */
            multiplier: number;
            /** N Exceptions */
            n_exceptions: number;
            /** N Obs */
            n_obs: number;
            /** Plus Factor */
            plus_factor: number;
            /** Regulatory Window */
            regulatory_window: boolean;
            /**
             * Zone
             * @enum {string}
             */
            zone: "GREEN" | "AMBER" | "RED";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VegaExposure */
        VegaExposure: {
            /** Desk Code */
            desk_code: string;
            /** Factor Code */
            factor_code: string;
            /** Value */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backtest_pla_api_v1_backtest_pla_get: {
        parameters: {
            query?: {
                /** @description 'FIRM', a desk code, or 'desk:CODE' */
                scope?: string;
                /** @description Trailing P&L days */
                window?: number;
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_summary_api_v1_backtest_summary_get: {
        parameters: {
            query?: {
                /** @description 'FIRM', a desk code, or 'desk:CODE' */
                scope?: string;
                model?: "HS" | "FHS";
                /** @description Trailing P&L days */
                window?: number;
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desk_decomposition_api_v1_desks__desk_code__decomposition_get: {
        parameters: {
            query?: {
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path: {
                desk_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeskDecomposition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desk_positions_api_v1_desks__desk_code__positions_get: {
        parameters: {
            query?: {
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path: {
                desk_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeskPositions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    factors_latest_api_v1_factors_latest_get: {
        parameters: {
            query?: {
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorsLatest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    modeldoc_api_v1_modeldoc_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDoc"];
                };
            };
        };
    };
    risk_exposures_api_v1_risk_exposures_get: {
        parameters: {
            query?: {
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyRateExposures"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_history_api_v1_risk_history_get: {
        parameters: {
            query?: {
                /** @description 'FIRM', a desk code, or 'desk:CODE' */
                scope?: string;
                /** @description Trailing run dates */
                window?: number;
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_movers_api_v1_risk_movers_get: {
        parameters: {
            query?: {
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
                /** @description Calendar days back for the delta baseline (drivers always describe the as-of day) */
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskMovers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_summary_api_v1_risk_summary_get: {
        parameters: {
            query?: {
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenarios_catalog_api_v1_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioCatalog"];
                };
            };
        };
    };
    scenarios_results_api_v1_scenarios_results_get: {
        parameters: {
            query?: {
                /** @description Pin to a run date (default: latest completed batch) */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
}
