"""Stress-calibration report - where the catalog's magnitudes come from.

    python -m risk.jobs.calibrate_stress [--snapshot ...] [--portfolio ...]

Writes docs/stress_calibration.md from the committed snapshot: the measured
severity of every hypothetical shock in the catalog (which quantile of the
book's own 20-day move history it sits at, and how many windows reached it),
the p99 reference magnitudes per factor, and the conditional tail mean that
calibrates the correlated risk-off scenario. Snapshot-only - no network, no
database - so the numbers regenerate bit-for-bit from the repo.

The report is the provenance record; scenarios/hypothetical_shocks.yaml keeps
the magnitudes with one-line citations back to it.
"""

from __future__ import annotations

import argparse
import datetime as dt

import yaml

from risk.db import code_version
from risk.jobs.backfill import load_inputs
from risk_engine.calibrate import (
    HORIZON_DAYS,
    calibration_meta,
    conditional_tail_mean,
    quantile_of,
    severity,
)
from risk_engine.stress import REPLAY_WINDOWS

OUT_PATH = "docs/stress_calibration.md"
SHOCKS_YAML = "scenarios/hypothetical_shocks.yaml"

# the factor each sensitivity scenario is measured against: a class moved
# uniformly is reported at its most-quoted member
CLASS_PROXY = {"IR": "IR.UST.10Y", "EQ": "EQ.SPY", "FX": "FX.EURUSD", "VOL": "VOL.SPX.IV30"}

UNIT = {"LOG": "log", "ABS_BP": "bp", "ABS": "pt"}


def _fmt(value: float, conv: str) -> str:
    if conv == "ABS_BP":
        return f"{value:+.0f}bp"
    if conv == "ABS":
        return f"{value:+.1f}pt"
    return f"{value:+.4f} log ({(pow(2.718281828459045, value) - 1) * 100:+.1f}%)"


def driver_shock(shocks: dict[str, dict]) -> tuple[str, dict]:
    """The scenario's headline shock. Magnitudes only compare within a
    convention - 20 vol points is not larger than a 0.223 log return - so the
    ranking runs inside the modal shock type, the one the scenario is named
    for."""
    counts: dict[str, int] = {}
    for s in shocks.values():
        counts[s["type"]] = counts.get(s["type"], 0) + 1
    modal = max(counts, key=lambda t: counts[t])
    same = {f: s for f, s in shocks.items() if s["type"] == modal}
    # a uniform ladder ties across its whole class: quote the class proxy
    # (the 10Y for rates, SPY for equities) rather than whichever came first
    proxies = set(CLASS_PROXY.values())
    return max(same.items(),
               key=lambda kv: (abs(kv[1]["value"]), kv[0] in proxies))


def build_report(returns, convs: dict[str, str], hypos: list[dict]) -> str:
    meta = calibration_meta(returns)
    out: list[str] = []
    add = out.append

    add("# Stress calibration\n")
    add(f"Generated by `python -m risk.jobs.calibrate_stress` at `{code_version()}` "
        f"from the committed snapshot. Do not edit by hand.\n")
    add(f"Basis: overlapping **{meta.horizon_days}-business-day** moves, "
        f"{meta.n_windows:,} windows spanning {meta.start} to {meta.end}, each factor in "
        "its own return convention (log returns, basis points, vol points).\n")
    add("A one-month horizon is long enough to contain an episode and short enough that "
        "the book's positions would plausibly still be on. Overlapping windows keep every "
        "observed episode in the sample at the cost of correlated draws - the same trade "
        "the RNIV note makes for k-day shocks, and the reason severities below are quoted "
        "as quantiles rather than return periods.\n")

    add("## Catalog severities\n")
    add("Each hypothetical's largest shock, and where that magnitude sits in the measured "
        "distribution of the factor it moves.\n")
    add("| scenario | class | headline shock | quantile of \\|20d\\| | windows at or beyond |")
    add("|---|---|---|---|---|")
    for h in hypos:
        driver, spec = driver_shock(h["shocks"])
        conv = convs[driver]
        q, hits = quantile_of(returns, driver, spec["value"])
        add(f"| {h['code']} | {h.get('class', '-')} | {driver} {_fmt(spec['value'], conv)} | "
            f"{q * 100:.2f}% | {hits} of {meta.n_windows:,} |")
    add("")

    add(f"## Reference magnitudes (p{meta.severity_q * 100:.0f} of |{meta.horizon_days}d| moves)\n")
    add("What a stated-quantile calibration would imply per factor, for comparison with "
        "the catalog's round supervisory-style magnitudes.\n")
    add("| factor | unit | p99 magnitude |")
    add("|---|---|---|")
    for factor in returns.columns:
        conv = convs[factor]
        add(f"| {factor} | {UNIT[conv]} | {_fmt(severity(returns, factor), conv)} |")
    add("")

    driver = CLASS_PROXY["EQ"]
    add(f"## Conditional tail mean (driver {driver})\n")
    add(f"Mean move of every factor over the windows where {driver} sat at or below its "
        f"{meta.driver_tail_q:.0%} quantile - the co-movement the data delivered when "
        "equities sold off, which is how the correlated risk-off scenario is calibrated "
        "rather than by reusing one magnitude across classes.\n")
    ctm = conditional_tail_mean(returns, driver)
    add("| factor | conditional mean |")
    add("|---|---|")
    for factor in returns.columns:
        add(f"| {factor} | {_fmt(float(ctm[factor]), convs[factor])} |")
    add("")

    add("## Historical replays\n")
    add("Replays carry no chosen magnitudes - the window is the input and the shock is "
        "whatever the market delivered.\n")
    add("| scenario | window | SPY | UST 10Y | JPYUSD |")
    add("|---|---|---|---|---|")
    for code, (start, end) in REPLAY_WINDOWS.items():
        w = returns.loc[str(start):str(end)].sum()
        add(f"| {code} | {start} to {end} | {_fmt(float(w['EQ.SPY']), 'LOG')} | "
            f"{_fmt(float(w['IR.UST.10Y']), 'ABS_BP')} | "
            f"{_fmt(float(w['FX.JPYUSD']), 'LOG')} |")
    add("")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="risk.jobs.calibrate_stress")
    parser.add_argument("--snapshot", default="data/seed/market_snapshot.parquet")
    parser.add_argument("--portfolio", default="data/seed/portfolio.yaml")
    parser.add_argument("--out", default=OUT_PATH)
    args = parser.parse_args(argv)

    _, _, returns, _ = load_inputs(args.snapshot, args.portfolio)
    cfg = yaml.safe_load(open(args.portfolio))
    convs = {f["code"]: f["conv"] for f in cfg["factors"]}
    hypos = yaml.safe_load(open(SHOCKS_YAML))

    report = build_report(returns, convs, hypos)
    with open(args.out, "w") as fh:
        fh.write(report)
    print(f"[calibrate] wrote {args.out} ({len(report.splitlines())} lines, "
          f"horizon {HORIZON_DAYS}d, generated {dt.date.today()})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
