"""Risks-not-in-VaR measurements: quantifying the model's documented blind spots.

Banks maintain an RNIV inventory - every known limitation of the VaR model gets
a measured impact, a materiality class, and a treatment, reviewed by committee.
This module holds the pure measurements behind docs/rniv.md (generated by
risk/jobs/rniv.py); each corresponds to an entry in the model doc's section 5.

All functions are deterministic transforms of the committed snapshot - no
database, no network, no clock.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

import pandas as pd

from .factors import build_scenarios_hs
from .var import ewma_vol_forecast

MIN_OBS_FOR_VOL = 40    # per-factor floor before a damping ratio is meaningful


def kday_overlapping_shocks(returns: pd.DataFrame, as_of, k: int,
                            lookback: int = 500) -> pd.DataFrame:
    """Overlapping k-day shocks from the same trailing window the 1-day VaR uses.

    Daily returns are additive under every convention here (log, bp, points),
    so a k-day shock is a rolling k-sum; the window yields lookback - k + 1
    scenarios. Overlap makes scenarios serially dependent - the effective
    sample is roughly lookback / k independent draws, and callers report the
    result as an estimate, not a second model.
    """
    if k < 2:
        raise ValueError(f"k={k}: use the daily scenario set for 1-day figures")
    window = build_scenarios_hs(returns, as_of, lookback)
    return window.rolling(k).sum().dropna()


def desk_scales_for_mix(standalone_var: Mapping[str, float],
                        target_shares: Mapping[str, float],
                        anchor: str) -> dict[str, float]:
    """Desk multipliers that move standalone-VaR shares onto target_shares.

    Historical-simulation VaR is positively homogeneous of degree one in a
    desk's quantities: scaling a desk multiplies its whole P&L column, so its
    order statistics scale by the same factor exactly. The multipliers are
    therefore closed form rather than a search - c_i proportional to
    target_i / share_i - and the achieved mix equals the target identically.

    Overall book scale is free (shares are normalized), so `anchor`'s multiplier
    is pinned to 1.0 and the others move around it. That keeps a mix change from
    silently doubling the book, which would confound a mix effect with a size
    effect.
    """
    missing = sorted(set(target_shares) - set(standalone_var))
    if missing:
        raise ValueError(f"no standalone VaR for target desks: {missing}")
    if anchor not in target_shares:
        raise ValueError(f"anchor {anchor!r} is not among the target desks")
    total = float(sum(standalone_var[d] for d in target_shares))
    if total <= 0.0:
        raise ValueError("standalone VaR sums to zero - nothing to reweight")
    raw = {}
    for desk, target in target_shares.items():
        share = float(standalone_var[desk]) / total
        if share <= 0.0:
            raise ValueError(f"{desk} carries no standalone VaR - cannot reweight it")
        raw[desk] = float(target) / share
    return {desk: value / raw[anchor] for desk, value in raw.items()}


def fill_mask(levels: pd.DataFrame, ffill_limits: Mapping[str, int]) -> pd.DataFrame:
    """True where align_levels would synthesize the cell (raw NaN, filled within
    the factor's cap). Mirrors align_levels so the two never drift."""
    out = {}
    for col in levels.columns:
        limit = int(ffill_limits.get(col, 3))
        filled = levels[col].ffill(limit=limit)
        out[col] = filled.notna() & levels[col].isna()
    return pd.DataFrame(out, index=levels.index)


def vol_damping_ratios(returns: pd.DataFrame, filled: pd.DataFrame, lam: float,
                       seed_window: int) -> pd.Series:
    """Per-factor forecast-vol ratio: excluding fill-day returns vs including.

    A forward-filled level imprints a zero return (and shifts the true move to
    the next print), damping EWMA vol. The ratio sigma_excl / sigma_incl >= ~1
    measures that damping at the forecast point; factors without enough
    history after exclusion return NaN rather than a fabricated ratio.
    """
    filled = filled.reindex(returns.index).fillna(False)
    out = {}
    for col in returns.columns:
        full = returns[[col]].dropna()
        compact = returns.loc[~filled[col], [col]].dropna()
        if len(compact) <= MIN_OBS_FOR_VOL or len(full) <= MIN_OBS_FOR_VOL:
            out[col] = float("nan")
            continue
        fc_full = float(ewma_vol_forecast(full, lam=lam).iloc[0])
        fc_compact = float(ewma_vol_forecast(compact, lam=lam).iloc[0])
        out[col] = fc_compact / fc_full if fc_full > 0 else float("nan")
    return pd.Series(out, name="vol_damping_ratio")


def lead_lag_correlations(returns: pd.DataFrame, left_cols: Sequence[str],
                          right_cols: Sequence[str], lags: Sequence[int] = (-1, 0, 1),
                          window: int = 500) -> pd.DataFrame:
    """corr(left_t, right_{t+lag}) over the trailing window, tidy.

    Asynchronous closes push same-day co-movement into the +/-1 lags: a noon
    FX fixing cannot see the afternoon equity move, so it shows up at lag +1.
    """
    tail = returns.tail(window)
    rows = []
    for lft in left_cols:
        for rgt in right_cols:
            for lag in lags:
                rows.append({"left": lft, "right": rgt, "lag": int(lag),
                             "corr": float(tail[lft].corr(tail[rgt].shift(-lag)))})
    return pd.DataFrame(rows)
